In [14]:
import os
import time
import json
import requests
import pandas as pd

from pathlib import Path
from difflib import SequenceMatcher
from dotenv import load_dotenv

In [ ]:
load_dotenv()

NYT_API_KEY = os.getenv("NYT_API_KEY")

START_YEAR = 2004
END_YEAR = 2024
SAMPLE_SIZE = 25

DATA_RAW = Path("data/raw")
DATA_PROCESSED = Path("data/processed")
DATA_CACHE = Path("data/cache/nyt")

DATA_RAW.mkdir(parents=True, exist_ok=True)
DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
DATA_CACHE.mkdir(parents=True, exist_ok=True)

NYT_ARTICLE_SEARCH_URL = "https://api.nytimes.com/svc/search/v2/articlesearch.json"

if not NYT_API_KEY:
    raise ValueError("Missing NYT_API_KEY in .env")

In [ ]:
DATA_RAW = Path("data/raw")

basics_path = DATA_RAW / "title.basics.tsv"
akas_path = DATA_RAW / "title.akas.tsv"

basics = pd.read_csv(
    basics_path,
    sep="\t",
    na_values="\\N",
    low_memory=False
)

akas = pd.read_csv(
    akas_path,
    sep="\t",
    na_values="\\N",
    low_memory=False
)

basics["startYear"] = pd.to_numeric(basics["startYear"], errors="coerce")

In [64]:
movies = basics[
    (basics["titleType"] == "movie") &
    (basics["startYear"].between(2004, 2024)) &
    (basics["isAdult"] == 0)
].copy()

us_titles = akas[akas["region"] == "US"].copy()

us_movies = movies.merge(
    us_titles[["titleId", "title", "region"]],
    left_on="tconst",
    right_on="titleId",
    how="inner"
)
us_movies = us_movies.drop(columns="genres", errors="ignore")

In [72]:
import re

kaggle_df = pd.read_csv(
    DATA_RAW / "box_office_data_filtering(2000-2024).csv"
)

kaggle_df = kaggle_df.rename(columns={
    "Release Group": "kaggle_title",
    "Year": "kaggle_year",
    "Genres": "genres"
})

def normalize_title(title):
    if pd.isna(title):
        return None
    title = str(title).lower().strip()
    title = re.sub(r"[^a-z0-9\s]", "", title)
    title = re.sub(r"\s+", " ", title)
    return title

In [75]:
us_movies["normalized_title"] = us_movies["primaryTitle"].apply(normalize_title)
kaggle_df["normalized_title"] = kaggle_df["kaggle_title"].apply(normalize_title)

us_movies["startYear"] = pd.to_numeric(us_movies["startYear"], errors="coerce")
kaggle_df["kaggle_year"] = pd.to_numeric(kaggle_df["kaggle_year"], errors="coerce")

theatrical_movies = us_movies.merge(
    kaggle_df[["normalized_title", "kaggle_year","genres"]],
    left_on=["normalized_title", "startYear"],
    right_on=["normalized_title", "kaggle_year"],
    how="inner"
)

theatrical_movies = theatrical_movies.drop_duplicates(
    subset="tconst"
).reset_index(drop=True)

print(theatrical_movies.shape)

theatrical_movies[[
    "tconst",
    "primaryTitle",
    "startYear",
    "genres"
]].head()

(3881, 14)

,tconst,primaryTitle,startYear,genres
0,tt0120667,Fantastic Four,2005.0,"Action, Fantasy, Science Fiction"
1,tt0121164,Corpse Bride,2005.0,"Romance, Fantasy, Animation"
2,tt0121766,Star Wars: Episode III - Revenge of the Sith,2005.0,"Adventure, Action, Science Fiction"
3,tt0167190,Hellboy,2004.0,"Fantasy, Action"
4,tt0167456,Thunderbirds,2004.0,"Action, Adventure, Comedy, Family"

In [76]:
def safe_filename(text):
    return "".join(
        c if c.isalnum() else "_"
        for c in str(text).lower()
    )[:80]


def title_similarity(a, b):
    if pd.isna(a) or pd.isna(b):
        return 0

    return SequenceMatcher(
        None,
        str(a).lower(),
        str(b).lower()
    ).ratio()

In [77]:
def search_nyt_articles(title, year, max_pages=1, sleep_seconds=6):
    cache_path = DATA_CACHE / f"{safe_filename(title)}_{int(year)}.json"

    if cache_path.exists():
        with open(cache_path, "r", encoding="utf-8") as f:
            return json.load(f)

    all_docs = []

    for page in range(max_pages):
        params = {
            "q": title,
            "begin_date": f"{int(year)}0101",
            "end_date": f"{int(year)}1231",
            "sort": "relevance",
            "page": page,
            "api-key": NYT_API_KEY
        }

        response = requests.get(
            NYT_ARTICLE_SEARCH_URL,
            params=params,
            timeout=20
        )

        safe_url = response.url.replace(NYT_API_KEY, "[HIDDEN_KEY]")

        if response.status_code == 429:
            print("NYT rate limit hit. Stop and wait before continuing.")
            raise RuntimeError("NYT API rate limit hit")

        if response.status_code != 200:
            print(f"NYT status {response.status_code} for {title}: {safe_url}")
            print(response.text[:500])
            break

        docs = response.json().get("response", {}).get("docs") or []
        all_docs.extend(docs)

        if not docs:
            break

        time.sleep(sleep_seconds)

    with open(cache_path, "w", encoding="utf-8") as f:
        json.dump(all_docs, f, ensure_ascii=False, indent=2)

    return all_docs

In [78]:
def extract_nyt_review_features(title, year):
    docs = search_nyt_articles(title, year)

    movie_review_docs = [
        doc for doc in docs
        if doc.get("section_name") == "Movies"
        and doc.get("type_of_material") == "Review"
    ]

    if not movie_review_docs:
        return {
            "has_nyt_coverage": len(docs) > 0,
            "has_nyt_movie_review": False,
            "nyt_review_count": 0,
            "nyt_headline": None,
            "nyt_publication_date": None,
            "nyt_section": None,
            "nyt_material_type": None,
            "nyt_url": None
        }

    best_doc = movie_review_docs[0]

    headline = best_doc.get("headline", {}).get("main")
    pub_date = best_doc.get("pub_date")

    return {
        "has_nyt_coverage": len(docs) > 0,
        "has_nyt_movie_review": True,
        "nyt_review_count": len(movie_review_docs),
        "nyt_headline": headline,
        "nyt_publication_date": pub_date[:10] if pub_date else None,
        "nyt_section": best_doc.get("section_name"),
        "nyt_material_type": best_doc.get("type_of_material"),
        "nyt_url": best_doc.get("web_url")
    }

In [79]:
sample_movies = theatrical_movies.sample(
    min(SAMPLE_SIZE, len(us_movies)),
    random_state=42
).copy()

sample_movies = sample_movies[[
    "tconst",
    "primaryTitle",
    "startYear",
    "genres",
]].drop_duplicates()

sample_movies.head()

,tconst,primaryTitle,startYear,genres
3431,tt5998744,S Storm,2016.0,"Crime, Action, Thriller"
1018,tt0979434,Lottery Ticket,2010.0,Comedy
3270,tt4916630,Just Mercy,2019.0,"Drama, Crime, History"
3613,tt7390646,Black and Blue,2019.0,"Action, Crime, Drama, Thriller"
1200,tt10701074,Ponniyin Selvan: Part I,2022.0,"Action, Adventure"

In [80]:
rows = []

for _, movie in sample_movies.iterrows():
    title = movie["primaryTitle"]
    year = movie["startYear"]

    print(f"Searching NYT for: {title} ({int(year)})")

    row = movie.to_dict()

    try:
        review_features = extract_nyt_review_features(title, year)
        row.update(review_features)
    except RuntimeError:
        break

    rows.append(row)

nyt_sample_df = pd.DataFrame(rows)

nyt_sample_df.to_csv(
    DATA_PROCESSED / "imdb_nyt_review_sample.csv",
    index=False
)

print(nyt_sample_df.head(10))

Searching NYT for: S Storm (2016)
Searching NYT for: Lottery Ticket (2010)
Searching NYT for: Just Mercy (2019)
Searching NYT for: Black and Blue (2019)
Searching NYT for: Ponniyin Selvan: Part I (2022)
Searching NYT for: A Witness Out of the Blue (2019)
Searching NYT for: Love and Honor (2006)
NYT rate limit hit. Stop and wait before continuing.
       tconst               primaryTitle  startYear  \
0   tt5998744                    S Storm     2016.0
1   tt0979434             Lottery Ticket     2010.0
2   tt4916630                 Just Mercy     2019.0
3   tt7390646             Black and Blue     2019.0
4  tt10701074    Ponniyin Selvan: Part I     2022.0
5  tt11076480  A Witness Out of the Blue     2019.0

                           genres  has_nyt_coverage  has_nyt_movie_review  \
0         Crime, Action, Thriller              True                 False
1                          Comedy              True                  True
2           Drama, Crime, History              True                  True
3  Action, Crime, Drama, Thriller              True                  True
4               Action, Adventure             False                 False
5        Crime, Thriller, Mystery              True                 False

   nyt_review_count                                       nyt_headline  \
0                 0                                                NaN
1                 1                                Bow Wow Hits It Big
2                 2  ‘Just Mercy’ Review: Echoes of Jim Crow on Ala...
3                 1  ‘Black and Blue’ Review: A Cop Thriller for Ou...
4                 0                                                NaN
5                 0                                                NaN

  nyt_publication_date nyt_section nyt_material_type  \
0                  NaN         NaN               NaN
1           2010-08-20      Movies            Review
2           2019-12-24      Movies            Review
3           2019-10-24      Movies            Review
4                  NaN         NaN               NaN
5                  NaN         NaN               NaN

                                             nyt_url
0                                                NaN
1  https://www.nytimes.com/2010/08/20/movies/20lo...
2  https://www.nytimes.com/2019/12/24/movies/just...
3  https://www.nytimes.com/2019/10/24/movies/blac...
4                                                NaN
5                                                NaN

In [36]:
display(nyt_sample_df.head(25))

,tconst,primaryTitle,startYear,genres,has_us_imdb_title,has_nyt_coverage,has_nyt_movie_review,nyt_review_count,nyt_headline,nyt_publication_date,nyt_section,nyt_material_type,nyt_url
0,tt0375735,Enduring Love,2004.0,"Drama,Mystery,Romance",True,True,False,0,NaN,NaN,NaN,NaN,NaN
1,tt0430683,Today,2004.0,NaN,True,True,False,0,NaN,NaN,NaN,NaN,NaN
2,tt0398638,30 Miles,2004.0,"Drama,Thriller",True,True,False,0,NaN,NaN,NaN,NaN,NaN
3,tt0381681,Before Sunset,2004.0,"Drama,Romance",True,True,True,2,FILM IN REVIEW; 'Mayor of the Sunset Strip',2004-04-02,Movies,Review,https://www.nytimes.com/2004/04/02/movies/film...
4,tt0382691,Gilles' Wife,2004.0,Drama,True,True,False,0,NaN,NaN,NaN,NaN,NaN
5,tt0814004,The Altruist,2004.0,"Crime,Thriller",True,True,False,0,NaN,NaN,NaN,NaN,NaN
6,tt37749008,Altered Courses,2004.0,Drama,True,True,False,0,NaN,NaN,NaN,NaN,NaN
7,tt0392049,The Good Cop,2004.0,"Action,Comedy",True,True,False,0,NaN,NaN,NaN,NaN,NaN
8,tt2981652,Mike and the Mechanics: Live at Shepherds Bush...,2004.0,Music,True,True,False,0,NaN,NaN,NaN,NaN,NaN
9,tt0296572,The Chronicles of Riddick,2004.0,"Action,Adventure,Sci-Fi",True,True,True,1,FILM REVIEW; Signs of Testosterone Are All Ove...,2004-06-11,Movies,Review,https://www.nytimes.com/2004/06/11/movies/film...
10,tt0386087,Simple Revenge,2004.0,"Drama,Mystery,Thriller",True,True,False,0,NaN,NaN,NaN,NaN,NaN
11,tt0397402,Dropped Frames,2004.0,Drama,True,True,False,0,NaN,NaN,NaN,NaN,NaN
12,tt0465554,Other People's Mirrors,2004.0,Drama,True,True,False,0,NaN,NaN,NaN,NaN,NaN
13,tt0407337,Zen Noir,2004.0,"Comedy,Drama,Mystery",True,True,False,0,NaN,NaN,NaN,NaN,NaN
14,tt0327247,The Whole Ten Yards,2004.0,"Comedy,Crime,Thriller",True,True,True,1,FILM REVIEW; Trying to Make a Disaffected Tuli...,2004-04-09,Movies,Review,https://www.nytimes.com/2004/04/09/movies/film...
15,tt0325596,The I Inside,2004.0,"Mystery,Sci-Fi,Thriller",True,True,False,0,NaN,NaN,NaN,NaN,NaN
16,tt1544995,A Line for Every Occasion,2004.0,Drama,True,True,False,0,NaN,NaN,NaN,NaN,NaN

In [30]:
def debug_nyt_article_search(title, year, max_docs=10):
    params = {
        "q": title,
        "begin_date": f"{int(year)}0101",
        "end_date": f"{int(year)}1231",
        "sort": "relevance",
        "api-key": NYT_API_KEY
    }

    response = requests.get(
        NYT_ARTICLE_SEARCH_URL,
        params=params,
        timeout=20
    )

    safe_url = response.url.replace(NYT_API_KEY, "[HIDDEN_KEY]")

    print("STATUS:", response.status_code)
    print("URL:", safe_url)

    if response.status_code != 200:
        print(response.text[:1000])
        return []

    data = response.json()

    docs = data.get("response", {}).get("docs") or []

    print("DOC COUNT:", len(docs))
    print()

    for i, doc in enumerate(docs[:max_docs], start=1):
        print("=" * 80)
        print(f"RESULT {i}")
        print("HEADLINE:", doc.get("headline", {}).get("main"))
        print("SECTION:", doc.get("section_name"))
        print("TYPE:", doc.get("type_of_material"))
        print("DATE:", doc.get("pub_date"))
        print("URL:", doc.get("web_url"))

        abstract = doc.get("abstract")
        if abstract:
            print("ABSTRACT:", abstract)

        print()

    return docs

In [32]:
docs = debug_nyt_article_search("The Incredibles", 2004)

STATUS: 200
URL: https://api.nytimes.com/svc/search/v2/articlesearch.json?q=The+Incredibles&begin_date=20040101&end_date=20041231&sort=relevance&api-key=[HIDDEN_KEY]
DOC COUNT: 10

================================================================================
RESULT 1
HEADLINE: Arts, Briefly; The Incredible 'Incredibles'
SECTION: Arts
TYPE: News
DATE: 2004-11-15T05:00:00Z
URL: https://www.nytimes.com/2004/11/15/arts/movies/arts-briefly-the-incredible-incredibles.html
ABSTRACT: Arts, Briefly column; Disney-Pixar film The Incredibles dominates box office for second weekend in row, with estimated $51 million in box office sales; Warner Brothers' The Polar Express has disappointing first weekend, taking in $23.5 million; photo (S)

================================================================================
RESULT 2
HEADLINE: Disney and Pixar Score Again as 'The Incredibles' Opens Big
SECTION: Arts
TYPE: News
DATE: 2004-11-08T05:00:00Z
URL: https://www.nytimes.com/2004/11/08/movies/MoviesFeatures/disney-and-pixar-score-again-as-the-incredibles-opens.html
ABSTRACT: Pixar-Walt Disney Co computer-animated movie The Incredibles takes in estimated $70.7 million nationwide in its first weekend; Paramount's Alfie remake garners dismal $6.5 million, far below expectations; photo (M)

================================================================================
RESULT 3
HEADLINE: The Incredible Pietro
SECTION: Opinion
TYPE: Editorial
DATE: 2004-11-21T05:00:00Z
URL: https://www.nytimes.com/2004/11/21/opinion/opinionspecial/the-incredible-pietro.html
ABSTRACT: Editorial on Pietro Barberi, 24, who has been hired, despite lack of credentials and little experience, as senior accountant for Yonkers Board of Education at a salary of $90,100-a-year; how job search was conducted and why Barberi was hired remains a mystery

================================================================================
RESULT 4
HEADLINE: After 'The Incredibles,' Pixar Can Afford to Play Hard-to-Get
SECTION: Business
TYPE: News
DATE: 2004-11-15T05:00:00Z
URL: https://www.nytimes.com/2004/11/15/business/media/after-the-incredibles-pixar-can-afford-to-play-hardtoget.html
ABSTRACT: Pixar Animation Studios, whose joint venture with Walt Disney Co is set to expire in 2005, has yet to begin serious talks to determine its next distribution partner; chief executive Steven P Jobs cites outlook for shifts in top executives at studios; planned retirement of Michael D Eisner as Disney chief executive seen key factor; Jobs has always favored deal with Disney, but blamed Eisner for souring two companies' lucrative ties; photo (M)

================================================================================
RESULT 5
HEADLINE: The Incredible Shrinking Investment Bank
SECTION: Business
TYPE: News
DATE: 2004-10-17T05:00:00Z
URL: https://www.nytimes.com/2004/10/17/business/yourmoney/the-incredible-shrinking-investment-bank.html
ABSTRACT: Outlook for famous companies like Merrill Lynch and Morgan Stanley discussed in light of encroachments by universal banks such as Citigroup and J P Morgan, with their swollen balance sheets and ripe ambitions; investment bankers say two old-line firms are in similar quandaries but that Merrill faces most pressure to merge because it has become so much smaller; cite upcoming public offering of DreamWorks SKG's animation unit as example of how big banks use financial brawn and deal-making skill to muscle in on territory long owned by investment banks; photos; graphs showing stock declines this year for major Wall Street firms (M)

================================================================================
RESULT 6
HEADLINE: Time on a Chip: The Incredible Shrinking Atomic Clock
SECTION: Technology
TYPE: News
DATE: 2004-09-30T05:00:00Z
URL: https://www.nytimes.com/2004/09/30/technology/circuits/time-on-a-chip-the-incredible-shrinking-atomic-clock.html
ABSTRACT: What's Next column explores development of atomic clocks using standard semiconductor process; device would replace quartz oscillators used in watches and electronic devices; drawing (M)

================================================================================
RESULT 7
HEADLINE: HORSE RACING : Part sport, part spectacle, 'The Incredible Bet' lures fans in France
SECTION: Sports
TYPE: News
DATE: 2004-09-20T05:00:00Z
URL: https://www.nytimes.com/2004/09/20/sports/horse-racing-part-sport-part-spectacle-the-incredible-bet-lures-fans.html

================================================================================
RESULT 8
HEADLINE: Truth, Justice and the Middle-American Way
SECTION: Arts
TYPE: News
DATE: 2004-10-20T05:00:00Z
URL: https://www.nytimes.com/2004/10/20/movies/truth-justice-and-the-middleamerican-way.html
ABSTRACT: Article on Disney/Pixar's latest animated film, The Incredibles, due for release on November 5, whose hero, Bob Parr, middle-aged retired Superhero, exhibits more middle-American sensibility than usual fare from Hollywood; cartoon (M)

================================================================================
RESULT 9
HEADLINE: Pixar's Mr. Incredible May Yet Rewrite the Apple Story
SECTION: Business
TYPE: News
DATE: 2004-10-24T05:00:00Z
URL: https://www.nytimes.com/2004/10/24/business/yourmoney/pixars-mr-incredible-may-yet-rewrite-the-apple-story.html
ABSTRACT: Steven P Jobs' great success at helm of Pixar Animation Studios reviewed; photo; newest offering is The Incredibles, melding of superaction action and PG-rated comedy that could take in $519 million in worldwide box office after it opens in November; his masterstroke of emphasizing old-fashioned virtue of compelling storytelling noted (M)

================================================================================
RESULT 10
HEADLINE: ARCHITECTURE; The Incredible Shrinking Daniel Libeskind
SECTION: Arts
TYPE: News
DATE: 2004-06-20T05:00:00Z
URL: https://www.nytimes.com/2004/06/20/arts/architecture-the-incredible-shrinking-daniel-libeskind.html
ABSTRACT: Architect Daniel Libeskind, hailed last year as master planner of World Trade Center site, now plays far less visible role in redevelopment of downtown Manhattan; his influence, control and stature have steadily eroded as signature elements of his plan have been altered, reduced or eliminated; planning is now dominated by Port Authority of New York and New Jersey, which owns site, and by Skidmore, Owings & Merrill, architectural firm hired by Larry A Silverstein, site's leaseholder; Libeskind reportedly no longer attends meetings at which plans are discussed; photos (L)